DROP SCHEMA IF EXISTS HANGMAN_GAME;
CREATE SCHEMA IF NOT EXISTS HANGMAN_GAME;

USE HANGMAN_GAME;

-- WORDS TABLE
CREATE TABLE IF NOT EXISTS WORDS (
    WORD_ID INT AUTO_INCREMENT PRIMARY KEY,
    WORD VARCHAR(50) NOT NULL
);


-- IMAGES TABLE THAT IS USED AS A FK IN GAME TABLE TO GUESSES_REMAINING
CREATE TABLE IF NOT EXISTS IMAGES (
    IMAGE_ID INT PRIMARY KEY,
    IMAGE_URL VARCHAR(100)
);


-- GAMES TABLE
CREATE TABLE IF NOT EXISTS GAMES (
    GAME_ID INT AUTO_INCREMENT PRIMARY KEY,
    SESSION_ID VARCHAR(30) NOT NULL, -- store the port number of the user to keep track of session
    WORD_ID INT NOT NULL,
    INCORRECT_GUESSES INT DEFAULT 1, -- TYPICAL STARTING LIVES IN HANGMAN
    GAME_STATE ENUM('ONGOING', 'FINISHED') DEFAULT 'ONGOING',
    WIN_CONDITION INT NOT NULL,
    -- FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (WORD_ID) REFERENCES WORDS(WORD_ID)
    -- FOREIGN KEY (INCORRECT_GUESSES) REFERENCES IMAGES(IMAGE_ID)
);

--  create table to store each individual guess for each GAME
CREATE TABLE IF NOT EXISTS GUESSES (
    GUESS_ID INT AUTO_INCREMENT PRIMARY KEY,
    LETTER CHAR(1),
    GAME_ID INT,
    GUESSED_WORD VARCHAR(50),
    FOREIGN KEY (GAME_ID) REFERENCES GAMES(GAME_ID)
);


INSERT INTO WORDS (word) VALUES
('APPLE'),
('GUITAR'),
('BANANA'),
('DRAGON'),
('ZEBRA'),
('JELLYFISH'),
('PIANO'),
('MOUNTAIN'),
('LEMON'),
('TURTLE'),
('MUSHROOM'),
('CACTUS'),
('PAPER'),
('TRAIN'),
('CASTLE'),
('OCTOPUS'),
('PARROT'),
('BUTTERFLY'),
('CROCODILE'),
('VOLCANO'),
('SNOWFLAKE'),
('EMERALD'),
('PENGUIN'),
('BICYCLE'),
('FLAMINGO'),
('RAINBOW'),
('HEDGEHOG'),
('FIREPLACE'),
('WATERMELON'),
('SHARK'),
('DOLPHIN'),
('LAPTOP'),
('STRAWBERRY'),
('CALENDAR'),
('PUMPKIN'),
('ELEPHANT'),
('GIRAFFE'),
('SCISSORS'),
('TELESCOPE'),
('SUITCASE'),
('UMBRELLA'),
('KEYBOARD'),
('CANDLE'),
('CHOCOLATE'),
('KITE'),
('KANGAROO'),
('SUNRISE'),
('SEAHORSE');


INSERT INTO IMAGES VALUES (1, "images\\hangman-1.png"),(2, "images\\hangman-2.png"),(3, "images\\hangman-3.png"),(4, "images\\hangman-4.png"),(5, "images\\hangman-5.png"),(6, "images\\hangman-6.png"),(7, "images\\hangman-7.png"),(8, "images\\hangman-8.png");